name: CI/CD Pipeline for F1WebApp

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./F1WebAppBack
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Application Tests
      run: dotnet test F1.Tests/F1.Shared.ApplicationTests --configuration Release --no-build
    
    - name: Run Additional Tests (Ejemplo para futuros tests)
      if: false  # Deshabilitado por ahora
      run: dotnet test F1.Tests/F1.Shared.DomainTests --configuration Release --no-build

  automerge:
    needs: build-and-test
    if: github.ref == 'refs/heads/develop' && success()
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Merge develop into main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin main:main
        git checkout main
        git merge --no-ff origin/develop -m "Automerged develop into main [skip ci]"
        git push origin main
